export 'package:crm/presentation/add_lead/add_lead.screen.dart';
export 'package:crm/presentation/call_activities/call_activities.screen.dart';
export 'package:crm/presentation/check_in/check_in.screen.dart';
export 'package:crm/presentation/document_activities/document_activities.screen.dart';
export 'package:crm/presentation/face_scan/face_scan.screen.dart';
export 'package:crm/presentation/home/home.screen.dart';
export 'package:crm/presentation/login/login.screen.dart';
export 'package:crm/presentation/sna_form/sna_form.screen.dart';
export 'package:crm/presentation/splash_screen/splash_screen.screen.dart';